# Generated by Django 4.2.13 on 2024-06-04 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_ml', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='wateringested',
            name='amount_ml',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_tracker.cupsize'),
        ),
    ]
